version: "3.9"
services:
  distributed_project:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: rosuser
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    container_name: ros2_distributed_project
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - ./:/ros2_ws/src_DRP
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
    environment:
      - DISPLAY=${DISPLAY}
      - LIBGL_ALWAYS_INDIRECT=0
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=1
      - CYCLONEDDS_URI=file:///ros2_ws/cyclonedds.xml
      # questi export non vanno inseriti in quanto non funzioanno per i docker
      # - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      # - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    devices:
      - /dev/input/js0:/dev/input/js0  
    privileged: true
    command: bash