
/**:
  ros__parameters:
    map: "plane_2" # Maps can be "test_world" or "plane_2"
    init_names: ["minion1", "minion2"] # Names of the robots to be spawned
    init_rand: [false, false] # If true, the robots will be spawned in random positions
    init_x: [1.0, 1.0] # X position of the robots
    init_y: [2.0, 3.0] # Y position of the robots
    init_yaw: [0., 0.] # Yaw of the robots

    # init_names: ["minion1"] # Names of the robots to be spawned
    # init_rand: [false] # If true, the robots will be spawned in random positions
    # init_x: [5.0] # X position of the robots
    # init_y: [4.5] # Y position of the robots
    # init_yaw: [0.0] # Yaw of the robots

    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: transient_local
          history: keep_last
          reliability: reliable
topics:
  filtered_pcl: "filtered_pcl"
  cluster_pose: "c_position"
  cluster_pcl: "cluster_pcl"
  cluster_centroid: "median"
  voxel_estimate: "voxel_estimate"

filter_params:
  voxel_leaf_size: 0.05
      
minion_additions:
  max_camera_depth: 8.0
